<a href="https://colab.research.google.com/github/GokhanDonmez/AISEC_DL_ML/blob/main/LinearRegressionMultipleVariable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
import pandas as pd

In [5]:
df=pd.read_csv('/content/drive/MyDrive/YapayZeka/homepricesMulti.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
import math
median_bedrooms=math.floor(df.bedrooms.median())
median_bedrooms

4

In [7]:
df.bedrooms=df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [8]:
reg=linear_model.LinearRegression()

Burda multiple variable olduğu için fit methodumuza özelliklerimizi tek tek yazacağız

In [9]:
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [10]:
X_test = np.array([[3300, 3, 10]])
reg.predict(X_test)


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([628978.52142194])

In [11]:
import pickle

In [12]:
with open('model_pickle','wb') as f:
  pickle.dump(reg,f)

In [15]:
with open('/content/drive/MyDrive/YapayZeka/model_pickle','rb') as f:
  model=pickle.load(f)

In [16]:
model.predict(X_test)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([628978.52142194])

In [19]:
import joblib

In [20]:
joblib.dump(model,'/content/drive/MyDrive/YapayZeka/model_joblib')

['/content/drive/MyDrive/YapayZeka/model_joblib']

In [21]:
model.predict(X_test)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([628978.52142194])